"""empty message

Revision ID: 1bace3ac76c5
Revises: fe5d1f8e9d7d
Create Date: 2022-11-04 22:17:28.152016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bace3ac76c5'
down_revision = 'fe5d1f8e9d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'teste')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('teste', sa.VARCHAR(length=512), nullable=True))
    # ### end Alembic commands ###
