"""empty message

Revision ID: 4a680ccdcbc1
Revises: 
Create Date: 2022-11-05 21:28:41.939440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a680ccdcbc1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('fullname', sa.String(length=64), nullable=False),
    sa.Column('secret', sa.String(length=512), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('fullname', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_color', sa.String(length=10), nullable=False),
    sa.Column('vehicle_model', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('create_by', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['create_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    op.drop_table('customers')
    op.drop_table('users')
    # ### end Alembic commands ###
