"""empty message

Revision ID: fe5d1f8e9d7d
Revises: a689ffce3463
Create Date: 2022-11-04 22:16:43.529326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5d1f8e9d7d'
down_revision = 'a689ffce3463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('teste', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'teste')
    # ### end Alembic commands ###
